log_directory: "model_logs"
exp_group: "uss"
exp_name: "chen_bridge_sde-2mix_hive-dacvae-44k-4s-seqdit1d-betterdit-memsave-bsz4-accum2"
precision: "medium"

datamodule:
  data_name: WDSDataModule
  data_config:
    train_dir: /gpfs/hulab/public_datasets/audio_datasets/USS-Qwen/mix/curationed_data/train
    val_dir: /gpfs/hulab/public_datasets/audio_datasets/USS-Qwen/mix/curationed_data/val
    test_dir: /gpfs/hulab/public_datasets/audio_datasets/USS-Qwen/mix/curationed_data/test
    sample_rate: 44100
    batch_size: 4
    val_batch_size: 4
    val_tar_count: 8
    val_samples_per_tar: 500
    num_workers: 8
    shuffle_buffer: 1000
    drop_last: false
    persistent_workers: true
    mix_selected: [2mix]

step:
  save_checkpoint_every_n_steps: 10000
  max_steps: 200000
  save_top_k: 4
  limit_train_batches: 1000
  accumulate_grad_batches: 2

preprocessing:
  audio:
    sampling_rate: 44100
    max_wav_value: 32768.0
    duration: 4.16

model:
  target: models.dacbridge_seq.model.LatentDiffusionDACVAE1D
  params:
    base_learning_rate: 1.0e-05
    lr_warmup_steps: 10000
    lr_max: 1.0e-05
    lr_min: 1.0e-06
    lr_decay_until_step: 150000
    sampling_rate: 44100
    batchsize: 4
    linear_start: 0.0015
    linear_end: 0.0195
    timesteps: 1000
    unconditional_prob_cfg: 0.1
    first_stage_key: waveform
    latent_t_size: 104
    channels: 128
    extra_channels: true
    extra_channel_key: mixed_waveform
    scale_by_std: true
    sigma_min: 1.0e-04
    bridge_mode: true
    sb_schedule: true
    sb_rho: 1.0
    chen_bridge: true
    chen_sampler_type: "sde"
    data_prediction: true
    use_ei_solver: true
    backbone_config:
      target: models.dacbridge_seq.dit.DiT1D
      params:
        in_channels: 256
        out_channels: 256
        model_channels: 1024
        num_layers: 12
        num_heads: 16
        context_dim: 1024
        max_length: 104
        dropout: 0.1
        norm_eps: 1.0e-05
        qk_norm: true
        fc_bias: false
        ffn_exp: 4
        ffn_dim_multiplier: 1
        multiple_of: 64
        non_linearity: swiglu
        use_rope: true
        frequency_embedding_dim: 256
        timestep_non_linearity: swiglu
        t_block_non_linearity: silu
        t_block_bias: true
        context_non_linearity: swiglu
        context_embedder_dropout: 0.0
        context_norm: false
        patch_size: 1
        gradient_checkpointing: true
    first_stage_config:
      target: models.dacbridge_seq.first_stage.DACVAEFirstStage1D
      params:
        data_sample_rate: 44100
        duration: 4.16
        pretrained_model_name_or_path: facebook/sam-audio-large
    cond_stage_config:
      crossattn_text:
        cond_stage_key: caption
        conditioning_key: crossattn
        target: models.flowsep.text_encoder.FlanT5HiddenState
        params:
          emb_num: 1
          input_caption: true
    evaluation_params:
      unconditional_guidance_scale: 1.0
      ddim_sampling_steps: 50
      n_candidates_per_samples: 1
